codaisseur = School.create(name: "Codaisseur", city:"Amsterdam", rating: 5)

wouter = Teacher.create( name: "Wouter de Vos", nickname: "foxycoder", subject: "Full Stack Teacher", school:codaisseur , image:"https://codaisseur-production.s3.amazonaws.com/uploads/team_member/avatar/1/small_codaisseur-portraits-27-jpg-cb64901ab564a35a59906130ff5970bf.png")
miriam = Teacher.create( name: "Miriam Tocino", nickname: "miriamtocino", subject: "Ruby on Rails Teacher", school:codaisseur , image: "https://codaisseur-production.s3.amazonaws.com/uploads/team_member/avatar/4/small_img_20160328_194531-4-jpg-1427b38223729b91055f9196d175e34f.png")
ben = Teacher.create( name: "Benjamin Udink ten Cate", nickname: "hezus", subject: "Full Stack Teacher  ", school:codaisseur , image: "https://codaisseur-production.s3.amazonaws.com/uploads/team_member/avatar/7/small_ben-jpg-adab811bf5978dd98a280c8a3f81eec8.png")
rory = Teacher.create( name: "Rory Koehein", nickname: "nextminds", subject: "React & Javascript", school:codaisseur , image: "https://codaisseur-production.s3.amazonaws.com/uploads/team_member/avatar/5/small_rory-bw-jpg-2aa433d979259724eb9cd3daa44984d3.png")
tadeusz = Teacher.create( name: "Tadeusz Łazurski", nickname:"Izirski",  subject: "React & Javascript", school:codaisseur , image: "https://codaisseur-production.s3.amazonaws.com/uploads/team_member/avatar/8/small_tadeusz-jpeg-1601d28894359f944e9ad94b2c87c396.png")

sjon = User.create!(name:'Sjon Doe', email:'sjon@gmail.com', password: 'topsecret', password_confirmation:'topsecret')
brian = User.create!(name:'Brian Lens', email:'brianlens@gmail.com', password: 'topsecret', password_confirmation:'topsecret')
carla = User.create!(name:'Carla Bababababa', email:'carla@gmail.com', password: 'topsecret', password_confirmation:'topsecret')
laurence = User.create!(name:'Laurence Weening', email:'L03TJ3@gmail.com', password: 'topsecret', password_confirmation:'topsecret')
manoah = User.create!(name:'Manoah Upsjon', email:'upsjon@gmail.com', password: 'topsecret', password_confirmation:'topsecret')


Review.create( rating:4, description:"Lekker peuken roken buiten op de stoep samen, jatoch, mzzl", title:"Nice!", user:sjon, teacher:wouter )
Review.create( rating:4, description:"besameee mucho", title:"Goood!", user:sjon, teacher:miriam )
Review.create( rating:5, description:"Nice JS lessons", title:"Very Nice!", user:brian, teacher:ben)
Review.create( rating:4, description:"Learned a lot!", title:"Like!!11!one", user:carla, teacher:tadeusz )
Review.create( rating:3, description:"Sjon weet 't ook ff niet meer'", title:"Why does this need a title actually", user:sjon, teacher:tadeusz )
Review.create( rating:4, description:"Thanks for Asciinema", title:"LikezZ!1!one", user:laurence, teacher:wouter )
Review.create( rating:4, description:"Good lessons", title:"Good!", user:manoah, teacher:wouter )
Review.create( rating:4, description:"Was very nice :)", title:"¡Bueno!", user:carla, teacher:ben )
Review.create( rating:5, description:"She makes omelettes during lessons, so nice", title:"¡Bueno mucho!", user:carla, teacher:miriam)
Review.create( rating:3, description:"3/5 because sometimes still food in beard...", title:"Allright!", user:laurence, teacher:ben )
Review.create( rating:1, description:"The typing speed of this guy is too damn high", title:"Whut?!", user:manoah, teacher:rory )
Review.create( rating:4, description:"Si, si, si, aiaiaiaiai", title:"Me gusto", user:brian, teacher:miriam )
